apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: fixtures-rw
   labels:
      app: fixtures-rw
spec:
   replicas: 2
   selector:
      matchLabels:
         app: fixtures-rw
   template:
      metadata:
         labels:
            app: fixtures-rw
            version: "latest"
      spec:
         containers:
            -  name: fixtures-rw
               image: peteclarkio/fixtures-rw:v0.0.2
               ports:
                  -  name: http
                     containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: fixtures-rw
   labels:
      app: fixtures-rw
spec:
   type: LoadBalancer
   ports:
      - port: 80
        targetPort: http
   selector:
      app: fixtures-rw
